services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
